logging:
    logging_level: 7
    use_syslog: 0
    msg_tag: servo
    use_stdout: 1

servo:
    type: pi
    software_timestamp: 1
    step_threshold: 0.0
    first_step_threshold: 0.00002
    servo_offset_threshold: 0
    servo_num_offset_values: 0
    pi_proportional_const: 0.0
    pi_integral_const: 0.0
    pi_proportional_scale: 0.0
    pi_proportional_exponent: -0.3
    pi_proportional_norm_max: 0.7
    pi_integral_scale: 0.0
    pi_integral_exponent: 0.4
    pi_integral_norm_max: 0.3
    logMinDelayReqInterval: 0
    logSyncInterval: 0

device:
    monitor_uds_address: /var/run/monitor
    tsproc_mode: filter
    delay_filter: moving_median
    delay_filter_length: 10

